# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: pt

pipeline:
  - name: SpacyNLP
    model: pt_core_news_md
  - name: SpacyTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: SpacyFeaturizer
    pooling: mean
  - name: DIETClassifier
    epochs: 50
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 50
    retrieval_intent: faq
  - name: ResponseSelector
    epochs: 50
    retrieval_intent: papofurado
  - name: ResponseSelector
    epochs: 50
    retrieval_intent: parar
  - name: ResponseSelector
    epochs: 50
    retrieval_intent: menu
  - name: ResponseSelector
    epochs: 50
    retrieval_intent: finalizacao
  - name: ResponseSelector
    epochs: 50
    retrieval_intent: iniciar
  - name: ResponseSelector
    epochs: 50
    retrieval_intent: creditos
  - name: ResponseSelector
    epochs: 50
    retrieval_intent: pegar_carta
  - name: ResponseSelector
    epochs: 50
    retrieval_intent: estatisticas
  - name: ResponseSelector
    epochs: 50
    retrieval_intent: cancelar
  - name: FallbackClassifier
    threshold: 0.4
policies:
  - name: RulePolicy
